version: "3.8"

services:
  uploader:
    image: 'excel-documents-uploader'
    restart: on-failure
    build:
      context: ./ExcelDataUploader
      dockerfile: Dockerfile
    volumes:
      - ./ExcelDataUploader:/var/www/uploader
    environment:
      - COMPOSER_ENV=development

#TODO: Add worker to the uploader
  workeruploader:
    image: 'excel-documents-uploader'
    restart: on-failure
    build:
      context: ./ExcelDataUploader
      dockerfile: Dockerfile
    volumes:
      - ./ExcelDataUploader:/var/www/uploader
    command: bash -c 'php artisan optimize && php artisan queue:listen --tries=1'
    environment:
      - COMPOSER_ENV=development

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: documents
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3309:3306"

  web:
    image: 'web-server'
    restart: on-failure
    build:
      context: ./nginx
      dockerfile: Dockerfile
    working_dir: /var/www/
    volumes:
      - .:/var/www/
    env_file:
      - .env
    ports:
      - "8085:8080"
    depends_on:
      - uploader
    deploy:
      replicas: 1

#  vue-frontend:
#    build: frontend
#    ports:
#      - "3000:8080"
#    volumes:
#      - ./frontend:/app
#    depends_on:
#      - uploader

volumes:
  mysql-data: {}
